POST https://render-service-odnr.onrender.com/api/notes
Content-Type: application/json 

{
	content: "there is a method known as HEAD ",
	important: true
}


###
GET https://render-service-odnr.onrender.com/api/notes

###

GET http://localhost:3001/api/notes
